version: '3.9'
services:
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 69:69/udp
    volumes:
      - isos:/app/iso
      - iventoy:/app/data
    environment:
      - AUTO_START_PXE=true # optional, true by default

volumes:
  isos:
    external: true
  iventoy:
    external: true