services:
  xo:
    #build: .
    image: interlegis/xen-orchestra:5.25.1
    ports:
      - "8000:80"
    links:
      - redis:redis
    volumes: 
      - 'xodata:/var/lib/xo-server/data'
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD="$xo-redis-pw"
    volumes: 
      - 'xoredisdata:/bitnami/redis'